# .github/workflows/deploy-lambda.yml
name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          
      - name: Install Dependencies
        run: npm ci
        
      - name: Build Project
        run: npm run build
        
      - name: Create Lambda Package
        run: |
          # Create a clean directory for the package
          mkdir -p lambda-package
          
          # Copy built files
          cp -r dist/* lambda-package/
          
          # Copy package.json and install production dependencies
          cp package.json lambda-package/
          cd lambda-package
          npm install --only=production --ignore-scripts
          cd ..
          
          # Create zip file
          cd lambda-package
          zip -r ../lambda.zip .
          cd ..
          
      - name: Debug Secrets (without exposing values)
        run: |
          echo "AWS_ACCESS_KEY_ID is set: ${{ secrets.AWS_ACCESS_KEY_ID != '' }}"
          echo "AWS_SECRET_ACCESS_KEY is set: ${{ secrets.AWS_SECRET_ACCESS_KEY != '' }}"
          echo "AWS_ACCESS_KEY_ID length: ${#AWS_ACCESS_KEY_ID}"
          echo "AWS_SECRET_ACCESS_KEY length: ${#AWS_SECRET_ACCESS_KEY}"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          
      - name: Configure AWS Credentials
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set default.region us-east-1
          
      - name: Deploy to Lambda
        run: |
          # Update function code
          aws lambda update-function-code \
            --function-name ${{ secrets.LAMBDA_FUNCTION_NAME }} \
            --zip-file fileb://lambda.zip
            
          # Update function configuration (optional)
          aws lambda update-function-configuration \
            --function-name ${{ secrets.LAMBDA_FUNCTION_NAME }} \
            --handler ${{ secrets.LAMBDA_HANDLER }} \
            --runtime ${{ secrets.RUNTIME }}
            
      - name: Verify Deployment
        run: |
          aws lambda get-function \
            --function-name ${{ secrets.LAMBDA_FUNCTION_NAME }} \
            --query 'Configuration.LastModified'